Repository TimeBank-Sparta/TimeBank, pull requests merged in 2025-04, with the labels that each got.

#36 Feat/#26 user service common
  docker-compose.yml
  gateway-service/Dockerfile
  gateway-service/src/main/java/com/timebank/gatewayservice/filter/JwtAuthenticationFilter.java
  user-service/build.gradle
  user-service/src/main/java/com/timebank/userservice/application/dto/request/auth/SignUpRequestDto.java
  user-service/src/main/java/com/timebank/userservice/application/dto/request/profile/UserProfileUpdateRequestDto.java
  user-service/src/main/java/com/timebank/userservice/application/dto/response/auth/LoginResponseDto.java
  user-service/src/main/java/com/timebank/userservice/application/service/auth/AuthService.java
  user-service/src/main/java/com/timebank/userservice/application/service/auth/RefreshTokenService.java
  user-service/src/main/java/com/timebank/userservice/application/service/auth/RefreshTokenServiceImpl.java
  user-service/src/main/java/com/timebank/userservice/application/service/profile/UserProfileService.java
  user-service/src/main/java/com/timebank/userservice/application/service/user/UserService.java
  user-service/src/main/java/com/timebank/userservice/domain/jwt/JwtProvider.java
  user-service/src/main/java/com/timebank/userservice/domain/jwt/RefreshTokenRepository.java
  user-service/src/main/java/com/timebank/userservice/domain/model/profile/UserProfile.java
  user-service/src/main/java/com/timebank/userservice/domain/model/user/User.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/client/PointServiceClient.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/client/dto/PointAccountResponseDto.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/jwt/JwtUtil.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/jwt/RefreshTokenRepositoryImpl.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/redis/RedisConfig.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/util/JwtUtil.java
  user-service/src/main/java/com/timebank/userservice/presentation/controller/auth/AuthController.java
  user-service/src/main/java/com/timebank/userservice/presentation/controller/profile/UserProfileController.java
  user-service/src/main/java/com/timebank/userservice/presentation/controller/user/UserController.java
  user-service/src/main/java/com/timebank/userservice/presentation/dto/request/RefreshTokenRequestDto.java
  user-service/src/main/java/com/timebank/userservice/presentation/dto/response/TokenResponseDto.java
  user-service/src/main/resources/application.yml
Labels: enhancement

#42 Feat/#32 help service kafka
  help-service/build.gradle
  help-service/src/main/java/com/timebank/helpservice/HelpServiceApplication.java
  help-service/src/main/java/com/timebank/helpservice/global/confing/ProducerKafkaConfig.java
  help-service/src/main/java/com/timebank/helpservice/help_request/application/dto/request/HelpRequestToHelperKafkaDto.java
  help-service/src/main/java/com/timebank/helpservice/help_request/application/dto/response/HelpRequestResponse.java
  help-service/src/main/java/com/timebank/helpservice/help_request/application/service/HelpRequestEventProducer.java
  help-service/src/main/java/com/timebank/helpservice/help_request/application/service/HelpRequestService.java
  help-service/src/main/java/com/timebank/helpservice/help_request/domain/model/HelpRequest.java
  help-service/src/main/java/com/timebank/helpservice/help_request/domain/repository/HelpRequestRepository.java
  help-service/src/main/java/com/timebank/helpservice/help_request/infrastructure/messeging/HelpRequestKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/help_request/presentation/external/HelpRequestExternalController.java
  help-service/src/main/java/com/timebank/helpservice/help_request/presentation/internal/HelpRequestInternalController.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/dto/response/FromHelperKafkaDto.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/service/HelpTradingService.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/domain/model/HelpTrading.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/infrastructure/config/HelpTradingKafkaConsumerConfig.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/infrastructure/messaging/HelpTradingEventKafkaListener.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/infrastructure/messaging/KafkaMessageParser.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/client/HelpRequestClient.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/request/HelpRequestFeignDto.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/request/HelperToTradingKafkaDto.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/response/FromHelpRequestKafkaDto.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/service/HelperEventProducer.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/service/HelperService.java
  help-service/src/main/java/com/timebank/helpservice/helper/domain/repository/HelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/config/KafkaConsumerConfig.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepositoryCustom.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepositoryCustomImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/feign/HelpRequestFeignClient.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/feign/HelpRequestFeignClientImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/messaing/HelperEventKafkaListener.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/messaing/HelperKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/messaing/KafkaMessageParser.java
  help-service/src/test/http/HelpRequest.http
  help-service/src/test/http/Helper.http
Labels: enhancement

#56 Feat/#53 user service feign
  point-service/src/main/java/com/timebank/pointservice/application/dto/GetAccountResponseDto.java
  point-service/src/main/java/com/timebank/pointservice/application/service/PointService.java
  point-service/src/main/java/com/timebank/pointservice/presentation/controller/PointController.java
  user-service/src/main/java/com/timebank/userservice/application/dto/response/profile/UserMyProfileResponseDto.java
  user-service/src/main/java/com/timebank/userservice/application/service/auth/AuthService.java
  user-service/src/main/java/com/timebank/userservice/application/service/profile/UserProfileService.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/client/PointServiceClient.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/client/ReviewClient2.java
  user-service/src/main/java/com/timebank/userservice/infrastructure/client/dto/PointAccountResponseDto.java
  user-service/src/main/java/com/timebank/userservice/presentation/controller/profile/UserProfileController.java
Labels: enhancement

#57 55 feat help service test modify
  help-service/src/main/java/com/timebank/helpservice/help_request/application/dto/request/CreateHelpRequestCommand.java
  help-service/src/main/java/com/timebank/helpservice/help_request/application/service/HelpRequestService.java
  help-service/src/main/java/com/timebank/helpservice/help_request/infrastructure/messeging/HelpRequestKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/help_request/presentation/dto/request/CreateHelpRequest.java
  help-service/src/main/java/com/timebank/helpservice/help_request/presentation/external/HelpRequestExternalController.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/service/HelpTradingService.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/infrastructure/messaging/HelpTradingKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/request/CreateHelperCommand.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/response/FindHelperResponse.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/response/GetUserInfoFeignResponse.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/service/HelperService.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepositoryCustomImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/feign/UserFeignClient.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/messaing/HelperKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/helper/presentation/HelperController.java
  help-service/src/main/java/com/timebank/helpservice/helper/presentation/dto/request/CreateHelperRequest.java
Labels: bug

#65 Feat/#61 add helprequest cancle
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/dto/response/CancelTradingResponse.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/service/HelpTradingEventProducer.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/service/HelpTradingService.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/infrastructure/messaging/HelpTradingKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/presentation/HelpTradingController.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/service/HelperService.java
  help-service/src/main/java/com/timebank/helpservice/helper/domain/repository/HelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/db/JpaHelperRepositoryCustomImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/presentation/dto/request/CreateHelperRequest.java
Labels: bug, enhancement

#70 feat: helper responsedto 수정
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/response/AcceptHelperResponse.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/response/CreateHelperResponse.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/service/HelperService.java
  help-service/src/main/java/com/timebank/helpservice/helper/presentation/HelperController.java
Labels: enhancement

#101 Feat/#66 monitoring help-service modify
  docker-compose.yml
  help-service/build.gradle
  help-service/src/main/generated/com/timebank/helpservice/help_trading/domain/model/QHelpTrading.java
  help-service/src/main/java/com/timebank/helpservice/help_request/application/service/HelpRequestService.java
  help-service/src/main/java/com/timebank/helpservice/help_request/domain/model/HelpRequest.java
  help-service/src/main/java/com/timebank/helpservice/help_request/infrastructure/db/HelpRequestRepositoryImpl.java
  help-service/src/main/java/com/timebank/helpservice/help_request/infrastructure/messeging/HelpRequestKafkaProducer.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/dto/response/CreateTradingResponse.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/application/dto/response/FindHelpTradingResponse.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/domain/model/HelpTrading.java
  help-service/src/main/java/com/timebank/helpservice/help_trading/domain/vo/HelpTradingInfo.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/dto/response/FindHelperInfoResponse.java
  help-service/src/main/java/com/timebank/helpservice/helper/application/service/HelperService.java
  help-service/src/main/java/com/timebank/helpservice/helper/domain/vo/HelperInfo.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/HelperRepositoryImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/config/RedisConfig.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/feign/HelpRequestFeignClient.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/jpa/JpaHelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/jpa/JpaHelperRepositoryCustom.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/jpa/JpaHelperRepositoryCustomImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/messaing/HelperEventKafkaListener.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/redis/RedisHelperRepository.java
  help-service/src/main/java/com/timebank/helpservice/helper/infrastructure/redis/RedisHelperRepositoryImpl.java
  help-service/src/main/java/com/timebank/helpservice/helper/presentation/HelperController.java
  help-service/src/main/resources/application-test.yml
  help-service/src/main/resources/application.yml
  notification-service/build.gradle
  point-service/build.gradle
  prometheus.yml
  user-service/build.gradle
  user-service/src/main/java/com/timebank/userservice/infrastructure/config/SecurityConfig.java
Labels: enhancement
